// apps/demos/src/spinner/SpinnerSizes.tsx
import { Spinner } from '@spec-lab/ui-react';

export function SpinnerSizes() {
  return (
    <div className="flex items-center gap-8">
      <div className="flex flex-col items-center gap-2">
        <Spinner size="sm" />
        <span className="text-xs text-muted-foreground">Small</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Spinner size="md" />
        <span className="text-xs text-muted-foreground">Medium</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Spinner size="lg" />
        <span className="text-xs text-muted-foreground">Large</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Spinner size="xl" />
        <span className="text-xs text-muted-foreground">Extra Large</span>
      </div>
    </div>
  );
}

// legacy/examples/demos/spinner/SpinnerSizes.vue
<script setup>
  import Spinner from '@/components/spinner/spinner.vue';
</script>

<template>
  <div class="acv-grid-row acv-grid--cols-4">
    <div class="acv-grid-col">
      <Spinner size="small" />
    </div>
    <div class="acv-grid-col">
      <Spinner size="medium" />
    </div>
    <div class="acv-grid-col">
      <Spinner size="large" />
    </div>
    <div class="acv-grid-col">
      <Spinner size="x-large" />
    </div>
  </div>
</template>
