// apps/demos/src/checkbox/CheckboxStates.tsx
import { Checkbox, Label } from '@constructor-lab/ui-react';

export function CheckboxStates() {
  return (
    <div className="grid grid-cols-2 gap-6">
      <div className="space-y-3">
        <p className="text-sm font-medium">Unchecked States</p>
        <div className="flex items-center space-x-2">
          <Checkbox id="state-default" />
          <Label htmlFor="state-default" className="text-sm font-normal">
            Default
          </Label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="state-disabled-unchecked" disabled />
          <Label
            htmlFor="state-disabled-unchecked"
            className="text-sm font-normal text-[hsl(var(--checkbox-disabled-text)/0.4)]"
          >
            Disabled
          </Label>
        </div>
      </div>
      <div className="space-y-3">
        <p className="text-sm font-medium">Checked States</p>
        <div className="flex items-center space-x-2">
          <Checkbox id="state-checked" checked />
          <Label htmlFor="state-checked" className="text-sm font-normal">
            Checked
          </Label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="state-indeterminate" indeterminate />
          <Label htmlFor="state-indeterminate" className="text-sm font-normal">
            Indeterminate
          </Label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="state-disabled-checked" disabled checked />
          <Label
            htmlFor="state-disabled-checked"
            className="text-sm font-normal text-[hsl(var(--checkbox-disabled-text)/0.4)]"
          >
            Disabled checked
          </Label>
        </div>
      </div>
    </div>
  );
}

// packages/demos/src/checkbox/CheckboxStates.vue
<script setup>
  import AcvCheckbox from '@/components/checkbox/checkbox.vue';

  const checkboxStates = [
    '',
    'hover',
    'active',
    'invalid',
    'focus',
    'disabled',
  ];
  const checkboxValues = [
    'checked',
    'unchecked',
    'indeterminate'
  ];

  const valuesMap = {
    checked: true,
    unchecked: false,
    indeterminate: null
  };

  function getValue(value) {
    switch (value) {
      case 'checked':
        return true;
      case 'unchecked':
        return false;
      case 'indeterminate':
        return null;
    }
  }
</script>

<template>
  <div
    v-for="value in checkboxValues"
    :key="value"
    class="acv-grid-row acv-grid--cols-6 gap-4"
  >
    <div
      v-for="state in checkboxStates"
      :key="state"
    >
      <AcvCheckbox
        v-model="valuesMap[value]"
        :value="getValue(value)"
        :class="state"
        :invalid="state === 'invalid'"
        :disabled="state === 'disabled'"
        :label="`${state} ${value}`"
        :icon-class="state"
      />
    </div>
  </div>
</template>
